schemaVersion: 2.2.0
attributes:
  controller.devfile.io/storage-type: per-workspace
metadata:
  name: workspace-dev
components:
- name: podman
  container: 
    image: quay.io/cgruver0/che/podman-basic:latest
    ## image: nexus.clg.lab:5001/dev-spaces/podman-basic:latest
    memoryLimit: 6Gi
    mountSources: true
- volume:
    size: 4Gi
  name: projects
